### ISSUE TITLE
Hyper parameters for large scale experiments

### ISSUE THREAD

**Issue by zzhang1987** [kevinsbello/dagma#1]
Hi there, would you please provide the hyper parameters for large scale experiments?
I tries to use the hyper parameter for small scale exps, but it did not work.

Best,

Zhen Zhang

**Comment by kevinsbello** [comment]
Hi, I believe I only changed the L1 coefficient to 0.05, it could also help to increase the final max number of iterations a bit, e.g., form 6e4 to 7e4. Let me know if it works. -K

**Comment by zzhang1987** [comment]
L1 coefficient might be the reason. I believe smaller L1 coefficient may result in better performance.

**Comment by zzhang1987** [comment]
Also in the paper you have mentioned that you are using an 8-core E5-2860v4. I believe E5-2860v4 has more than 8 core. Do you mean 8-way (i.e. a very high-end machine with 8 E5-2860v4 cpu) or it is just a typo?

**Comment by kevinsbello** [comment]
Right, E5-2860v4 has more than 8 cores, however, I was restricted to use only 8-cores as I was using a shared resource :)

**Comment by zzhang1987** [comment]
Thanks for your helpful response. Now I believe the performance should be aligned with the ones reported in the paper.
