### ISSUE TITLE
Is it possible to restrict a node to have only incoming edges and no outgoing edges?

### ISSUE THREAD

**Issue by elmliu** [kevinsbello/dagma#2]

**Comment by kevinsbello** [comment]
Yes. For example, if you want to restrict node 5, you would have to fix the 5th row of W to zero in the optimization.
This is simpler to do for linear models, for MLPs it would get more tricky but I think is doable.

**Comment by sophiakrix** [comment]
Hi @kevinsbello , could you possibly explain how to restrict a non-linear DAGMA model in this way? Assuming there are real-world constraints, such that a node cannot have incoming edges, how would you adapt the code to fit this assumption?
